// keys for actiontypes
export const ActionTypes = {
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST',
  UPDATE_POST: 'UPDATE_POST',
  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  ERROR_SET: 'ERROR_SET',
  ERROR_CLEAR: 'ERROR_CLEAR',
  AUTH_USER: 'AUTH_USER',
  DEAUTH_USER: 'DEAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  USER_INFO: 'USER_INFO',
  USER_CLEAR: 'USER_CLEAR',
  UPDATE_USER: 'UPDATE_USER',
  EVENT_CREATE: 'EVENT_CREATE',
  FETCH_ORGS: 'FETCH_ORGS',
  FETCH_ORG: 'FETCH_ORG',
  FETCH_MENTORS: 'FETCH_MENTORS',
  FETCH_MENTOR: 'FETCH_MENTOR',
  FETCH_ALL: 'FETCH_ALL',
  FETCH_MESSAGED_MENTOR: 'FETCH_MESSAGED_MENTOR',
  MOMENTS_CLEAR: 'MOMENTS_CLEAR',
  MOMENT_CLEAR: 'MOMENT_CLEAR',
  CREATE_RESOURCE: 'CREATE_RESOURC',
  FETCH_RESOURCES: 'FETCH_RESOURCES',
  FETCH_RESOURCE: 'FETCH_RESOURCE',
  CLEAR_RESOURCE: 'CLEAR_RESOURCE',
  FETCH_EVENTS: 'FETCH_EVENTS',
  FETCH_EVENT: 'FETCH_EVENT',
  MENTOR_CLEAR: 'MENTOR_CLEAR',
  FETCH_MOMENTS: 'FETCH_MOMENTS',
  FETCH_MOMENT: 'FETCH_MOMENT',
  CREATE_MOMENT: 'CREATE_MOMENT',
};

export const ROOT_URL = 'https://foster-project.herokuapp.com/api';

export function errorClear() {
  return (dispatch) => {
    dispatch({ type: ActionTypes.ERROR_CLEAR });
  };
}
